Set RootVC
LubnaAly/authentication-app pull request #7
Opened 2024-09-26 12:21 UTC by LubnaAly

2024-09-26 17:54 UTC, MostafaNafie requested changes

2024-09-26 17:54 UTC, MostafaNafie commented on AuthenticationApp/View/Base.lproj/Main.storyboard
> +                        <outlet property="emailLabel" destination="64P-61-g3b" id="HKb-aX-lAR"/>
What is the purpose of this change?

2024-09-28 07:57 UTC, LubnaAly commented on AuthenticationApp/View/Base.lproj/Main.storyboard
> +                        <outlet property="emailLabel" destination="64P-61-g3b" id="HKb-aX-lAR"/>
Discarded.

2024-09-28 08:56 UTC, MostafaNafie approved these changes

2024-09-28 08:58 UTC, merged